Redesign landing page
wikispeedruns/wikipedia-speedruns pull request #401
Opened 2022-07-14 03:02 UTC by maggarwal99

Landing page redesign

Follow-up action items:
We should add a "quick play" mode to allow players to play random/custom prompts.

<img width="298" alt="Screen Shot 2022-07-13 at 8 00 59 PM" src="https://user-images.githubusercontent.com/35792356/178888862-642536eb-2807-49a7-bc27-29eb65164edb.png">
<img width="1552" alt="Screen Shot 2022-07-13 at 8 00 20 PM" src="https://user-images.githubusercontent.com/35792356/178888869-8bf583a1-e263-4d6d-b951-8d189d2d97b0.png">
<img width="1552" alt="Screen Shot 2022-07-13 at 7 59 32 PM" src="https://user-images.githubusercontent.com/35792356/178888876-346979fc-16a6-4503-b658-678c9c040620.png">
<img width="1552" alt="Screen Shot 2022-07-13 at 7 58 47 PM" src="https://user-images.githubusercontent.com/35792356/178888878-9ae12cf4-40d0-46c9-9339-1a2acdad688f.png">

2022-07-14 03:25 UTC, mliu59 commented
Will review soon, I think @danielliu04 said he wanted to try setting up the quick play thing. I'll create an issue and assign

2022-07-14 03:34 UTC, dqian3 commented
Looks great, only note is editor's pick should probably be renamed archive for now

2022-07-14 05:42 UTC, dqian3 requested changes
Please add the new logo I sent

2022-07-14 16:31 UTC, mliu59 commented
Yee I love this new UI, same comment as Dan about the archive section

2022-07-15 10:16 UTC, maggarwal99 commented
Made minor changes to the logo to be more consistent with Wikipedia's typography, hopefully, Oliver doesn't get upset _/\_

<img width="1552" alt="Screen Shot 2022-07-15 at 3 14 53 AM" src="https://user-images.githubusercontent.com/35792356/179203572-169c3267-c976-48a6-b318-ac641d875915.png">

2022-07-15 17:09 UTC, bricehalder commented on templates/home.html
> +                <h5 class="my-0">Prompt of the day</h5>
nit: I think "Prompt of the Day" would be better as this is a [title](https://capitalizemytitle.com/)

2022-07-17 15:20 UTC, merged