recommend quickplay prompts
wikispeedruns/wikipedia-speedruns pull request #450
Opened 2022-10-02 22:15 UTC by mliu59

2022-10-05 05:47 UTC, dqian3 requested changes
Small change. Also I would say that these shouldn't be hidden completely in a `<details>` element. Maybe show 1 or 2 and an option to see more. Also would be nice to see the time it was played, i.e. using `moment.js`

2022-10-05 05:47 UTC, dqian3 commented on config/default.json
> +    "MYSQL_USER": "root",
oops, put your local stuff in `config/prod.json`

2022-10-06 11:44 UTC, bricehalder commented
+ this would be an easy target to grief i.e. putting nsfw stuff in the quick plays box

2022-11-14 05:51 UTC, mliu59 commented
> plus this would be an easy target to grief i.e. putting nsfw stuff in the quick plays box.
> 
> Maybe instead of most recent, we could do something like most played in the past day or something?

I changed the suggested prompts to be random finished prompts from the past 3 days, so griefing would be practically unviable with sufficient traffic volume. I think griefing would be easier to do if it was just most played since they can just spam.

2023-11-27 16:01 UTC, dqian3 approved these changes

2023-11-27 16:01 UTC, merged