Start game automatically when spacebar is pressed
wikispeedruns/wikipedia-speedruns pull request #518
Opened 2023-11-19 04:28 UTC by scooterbreak

On the countdown page for Quick Play, if you press spacebar the game will automatically begin

2023-11-19 06:04 UTC, bricehalder approved these changes
Looks good, would like to see a picture or video to check design

2023-11-19 06:14 UTC, scooterbreak commented
Uploading Screen Recording 2023-11-18 at 10.13.58 PM.mov…

2023-11-19 06:14 UTC, scooterbreak commented
https://github.com/wikispeedruns/wikipedia-speedruns/assets/64957454/bb850f56-b4fb-4011-9496-d48a2ca7e845

2023-11-19 06:36 UTC, bricehalder requested changes

2023-11-19 06:36 UTC, bricehalder commented on static/js/modules/game/countdown.js
> +            <div><button id="start-btn" class="btn btn-outline-secondary">(Don't want to wait? Click here or press spacebar start immediately!)</button></div>
This is getting kind of wordy. Maybe just change to `Click here or press spacebar to start immediately!`

2023-11-21 00:58 UTC, dqian3 approved these changes
Looks good to me, just fix the typo and I'd be happy to merge :)

2023-11-21 01:00 UTC, dqian3 reviewed
A general note on deleting things:

Having a more systematic way to delete user data would be really nice, not just for this particular issue. We've also had people ask about deleting personal data, which we would have to do manually (and tbh I'm not sure if we've kept up with that). Going through and refactoring the SQL schema with CASCADE rules would help this along. This is a great first step though!

2023-11-21 02:27 UTC, mliu59 commented
> A general note on deleting things:
> 
> Having a more systematic way to delete user data would be really nice, not just for this particular issue. We've also had people ask about deleting personal data, which we would have to do manually (and tbh I'm not sure if we've kept up with that). Going through and refactoring the SQL schema with CASCADE rules would help this along. This is a great first step though!

Wrong PR? lol

2023-11-21 06:09 UTC, scooterbreak commented
Edited the message. Thanks!

2023-11-21 07:45 UTC, bricehalder approved these changes

2023-11-21 07:46 UTC, merged